title: Klopperz
markdown: GFM
description: 'Chronicles of klopperz and all the coding involved'
name: Klopperz
github_username:  klopperz
show_downloads: true
theme: jekyll-theme-minima
plugins:
  - jekyll-feed